image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo "init script"
  - init: echo 'start script'
  - init: nvm install v14.15.0
  - init: nvm use v14.15.0
  - init: npm install
  - init: echo 'done. "npm run dev" to start dev server'

vscode:
  extensions:
    - formulahendry.auto-close-tag@0.5.10:192223009a396fc39e5b915d5920c0f0
    - octref.vetur@0.23.0:TEzauMObB6f3i2JqlvrOpA==
